import ClientComponent from "./ClientComponent";
import "./globals.css";

export const metadata = {
  title: "Leet-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientComponent>{children}</ClientComponent>
      </body>
    </html>
  );
}
