/* eslint-disable @next/next/no-sync-scripts */
"use client";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { RecoilRoot } from "recoil";

export const metadata = {
  title: "Leet-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RecoilRoot>
          <ToastContainer />
          {children}
        </RecoilRoot>
      </body>
    </html>
  );
}
